run:
  categories:
  - cs.AI
  - cs.CV
  - cs.RO
  - cs.SY
  - math.OC
  - astro-ph.EP
  - physics.space-ph
  send_log: false
  log_dir: ./logs

fetch:
  days: 8
  max_results: 1000
  max_retries: 10

summarize:
  provider: modelscope
  api_key: env:MODELSCOPE_API_KEY
  base_url: https://api-inference.modelscope.cn/v1/
  model: Qwen/Qwen3-235B-A22B-Thinking-2507
  system_prompt: file:./prompts/summ_lm/system.md
  user_prompt_template: file:./prompts/summ_lm/user.md
  completion_options:
    temperature: 0.6

rate:
  strategy: llm
  top_k: 200
  max_selected: 10
  embedder: null
  llm:
    provider: modelscope
    api_key: env:MODELSCOPE_API_KEY
    base_url: https://api-inference.modelscope.cn/v1/
    model: Qwen/Qwen2.5-7B-Instruct
    system_prompt: file:./prompts/rate_lm/system.md
    user_prompt_template: file:./prompts/rate_lm/user.md
    completion_options:
      temperature: 0.2
      max_tokens: 1024

parse:
  enable_vlm: false
  tmp_dir: ./tmp

render:
  formats:
  - pdf
  - md
  output_dir: ./output
  base_filename: null

deliver:
  smtp_server: smtp.163.com
  port: 465
  sender: arxiv_bot@163.com
  recipient: arxiv_bot@163.com
  password: env:SMTP_PASSWORD

cache:
  dir: ~/.cache/arxiv-autosumm
  ttl_days: 16

batch:
  tmp_dir: ./tmp
  max_wait_hours: 24
  poll_interval_seconds: 30
  fallback_on_error: true
