run:
  categories:
  - cs.AI
  - cs.CV
  - cs.RO
  - cs.SY
  - math.OC
  - astro-ph.EP
  - physics.space-ph
  send_log: false
  log_dir: ./logs

fetch:
  days: 8
  max_results: 200
  max_retries: 10

summarize:
  provider: modelscope
  api_key: env:MODELSCOPE_API_KEY
  base_url: https://api-inference.modelscope.cn/v1/
  model: Qwen/Qwen3-235B-A22B-Thinking-2507
  batch: false
  system_prompt: file:./prompts/summ_lm/system.md
  user_prompt_template: file:./prompts/summ_lm/user.md
  completion_options:
    temperature: 0.6
  context_length: 131072

rate:
  strategy: llm
  top_k: 80
  max_selected: 10
  embedder: null
  llm:
    provider: modelscope
    api_key: env:MODELSCOPE_API_KEY
    base_url: https://api-inference.modelscope.cn/v1/
    model: Qwen/Qwen2.5-7B-Instruct
    batch: false
    system_prompt: file:./prompts/rate_lm/system.md
    user_prompt_template: file:./prompts/rate_lm/user.md
    completion_options:
      temperature: 0.2
      max_tokens: 1024
    context_length: 32768
    criteria:
      novelty:
        description: How original and innovative are the contributions?
        weight: 0.3
      methodology:
        description: How rigorous is the experimental design and evaluation?
        weight: 0.25
      clarity:
        description: How well-written and understandable is the paper?
        weight: 0.2

render:
  formats:
  - pdf
  - md
  output_dir: ./output
  base_filename: null

deliver:
  smtp_server: smtp.163.com
  port: 465
  sender: arxiv_bot@163.com
  recipient: kaupane20@yeah.net
  password: env:SMTP_PASSWORD
