run:
  categories:
  - cs.AI
  - cs.RO
  send_log: false
  log_dir: ./logs

fetch:
  days: 5
  max_results: env:FETCH_RESULTS
  max_retries: 10

summarize:
  provider: env:PROVIDER
  api_key: env:OPENROUTER_API_KEY
  base_url: null
  model: env:STRONG_MODEL
  batch: false
  system_prompt: file:./prompts/summ_lm/system.md
  user_prompt_template: file:./prompts/summ_lm/user.md
  completion_options:
    temperature: 1.0
  context_length: 200000

rate:
  strategy: llm
  max_selected: env:FINAL_RESULTS
  llm:
    provider: env:PROVIDER
    api_key: env:OPENROUTER_API_KEY
    base_url: null
    model: env:FAST_MODEL
    batch: false
    system_prompt: file:./prompts/rate_lm/system.md
    user_prompt_template: file:./prompts/rate_lm/user.md
    completion_options:
      temperature: 0.2
      max_tokens: 2048
    context_length: 100000
    criteria:
      novelty:
        description: How original and innovative are the contributions?
        weight: 0.3
      code/data-availability:
        description: Are implementations and datasets publicly available?
        weight: 0.25
      clarity:
        description: How well-written and understandable is the paper?
        weight: 0.25
      paradigm-shift-potential:
        description: Could this change how the field thinks?
        weight: 0.15
      fun-and-curiosity:
        description: How enjoyable would it be to code this? How much it makes you want to explore further?
        weight: 0.1
      conceptual-elegance:
        description: How beautiful is the approach, mathematics or the idea?
        weight: 0.1
      reputation:
        description: Give preference to research from well-known labs or organizations
        weight: 0.1

parse:
  enable_vlm: false
  tmp_dir: ./tmp
  fast_parser_timeout_seconds: 300

render:
  formats:
    - pdf
    - md
  output_dir: ./output
  base_filename: null

cache:
  dir: ~/.cache/arxiv-autosumm/
  ttl_days: 16

deliver:
  smtp_server: smtp.163.com
  port: 465
  sender: arxiv_bot@163.com
  recipient: env:RECIPIENT_EMAIL
  password: env:SMTP_PASSWORD
