run:
  categories:
  - cs.AI
  - cs.CV
  - cs.AI
  - cs.RO
  - math.OC
  - cs.RO
  - cs.CV
  - cs.RO
  send_log: true
  log_dir: ./logs

fetch:
  days: 16
  max_results: 768
  max_retries: 10

summarize:
  provider: dashscope
  api_key: var:DASHSCOPE_API_KEY
  base_url: https://dashscope.aliyuncs.com/compatible-mode/v1
  model: qwen3-max
  batch: true
  system_prompt: file:./prompts/summ_lm/system.md
  user_prompt_template: file:./prompts/summ_lm/user.md
  completion_options:
    temperature: 0.7
  context_length: 245760

rate:
  strategy: hybrid
  top_k: 100
  max_selected: 5
  embedder:
    provider: zhipu
    api_key: var:ZHIPU_API_KEY
    base_url: https://open.bigmodel.cn/api/paas/v4
    model: embedding-3
    batch: true
  llm:
    provider: zhipu
    api_key: var:ZHIPU_API_KEY
    base_url: https://open.bigmodel.cn/api/paas/v4
    model: glm-4.5-flash
    batch: true
    system_prompt: file:./prompts/rate_lm/system.md
    user_prompt_template: file:./prompts/rate_lm/user.md
    completion_options:
      temperature: 0.2
      max_tokens: 1024
    context_length: 122880
    criteria:
      novelty:
        description: How original and innovative are the contributions?
        weight: 0.3
      methodology:
        description: How rigorous is the experimental design and evaluation?
        weight: 0.25
      clarity:
        description: How well-written and understandable is the paper?
        weight: 0.2
      relevance:
        description: How relevant is this paper to your research interests?
        weight: 0.15
      impact:
        description: What is the potential impact of this work?
        weight: 0.1

parse:
  enable_vlm: true
  vlm:
    provider: zhipu
    api_key: var:ZHIPU_API_KEY
    base_url: https://open.bigmodel.cn/api/paas/v4
    model: glm-4v-flash
    batch: true
    system_prompt: file:./prompts/parse_vlm/system.md
    user_prompt: file:./prompts/parse_vlm/user.md
    complete_options:
      temperature: 0.3
    dpi: 224

render:
  formats:
  - pdf
  - md
  output_dir: ./output
  base_filename: null

cache:
  dir: ./cache
  ttl_days: 16

deliver:
  smtp_server: smtp.163.com
  port: 465
  sender: arxiv_bot@163.com
  recipient: var:RECIPIENT_EMAIL
  password: var:SMTP_PASSWORD
