run:
  categories:
  - cs.AI
  - cs.RO
  send_log: true
  log_dir: ./logs

fetch:
  days: 5
  max_results: 128
  max_retries: 10

summarize:
  provider: openrouter
  api_key: var:OPENROUTER_API_KEY
  base_url: https://openrouter.ai/api/v1
  model: openai/gpt-5
  batch: false
  system_prompt: file:./prompts/summ_lm/system.md
  user_prompt_template: file:./prompts/summ_lm/user.md
  completion_options:
    temperature: 1.0
  context_length: 400000

rate:
  strategy: llm
  max_selected: 5
  llm:
    provider: openrouter
    api_key: var:OPENROUTER_API_KEY
    base_url: https://openrouter.ai/api/v1
    model: nvidia/nemotron-nano-9b-v2:free
    batch: false
    system_prompt: file:./prompts/rate_lm/system.md
    user_prompt_template: file:./prompts/rate_lm/user.md
    completion_options:
      temperature: 0.2
      max_tokens: 1024
    context_length: 122880
    criteria:
      novelty:
        description: How original and innovative are the contributions?
        weight: 0.3
      methodology:
        description: How rigorous is the experimental design and evaluation?
        weight: 0.25
      clarity:
        description: How well-written and understandable is the paper?
        weight: 0.2
      relevance:
        description: How relevant is this paper to your research interests?
        weight: 0.15
      impact:
        description: What is the potential impact of this work?
        weight: 0.1

parse:
  enable_vlm: false
  tmp_dir: ./tmp
  fast_parser_timeout_seconds: 300

render:
  formats:
  - pdf
  output_dir: ./output
  base_filename: null

cache:
  dir: ./cache
  ttl_days: 16

deliver:
  smtp_server: smtp.163.com
  port: 465
  sender: arxiv_bot@163.com
  recipient: var:RECIPIENT_EMAIL
  password: var:SMTP_PASSWORD
