[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "autosumm"
version = "0.1.0"
description = "Automated ArXiv paper summarization pipeline"
authors = [{name = "Mtrya", email = "erchanmion20@outlook.com"}]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    arxiv,
    arxiv2text,
    fitz,
    json_repair,
    numpy,
    openai,
    pandas,
    pathlib,
    pydantic,
    pydantic_core,
    PyMuPDF,
    PyPDF2,
    PyYAML,
    regex,
    requests,
    scikit-learn,
    scipy,
    setuptools,
    tiktoken,
    tqdm
]

[project.scripts]
autosumm = "autosumm.cli:app"

[project.urls]
Homepage = "https://github.com/Mtrya/arxiv-autosumm"
Repository = "https://github.com/Mtrya/arxiv-autosumm"

[tool.setuptools.packages.find]
where = ["."]
include = ["autosumm*"]